//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCalendar_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ArtWorks
    {
        DiaryContainer db = new DiaryContainer();
        public int ArtWorkID { get; set; }
        public byte[] ArtworkThumbnail { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<long> ImageMimeType { get; set; }
        public Nullable<int> ID { get; set; }

        public Nullable<System.DateTime> DateAdded { get; set; }
        [NotMapped]
        public AppointmentDiary ImageEvent
        {
            get
            {
                return db.AppointmentDiary.Find(ID);
            }
        }
    }
}
