
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullCalendar_MVC
{

using System;
    using System.Collections.Generic;
    
public partial class Donation
{

    public System.Guid DonationID { get; set; }

    public Nullable<decimal> CurrentAmount { get; set; }

    public Nullable<decimal> TargetAmount { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string Background { get; set; }

    public Nullable<System.DateTime> DateSet { get; set; }

    public string DonationType { get; set; }

}

}
