
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullCalendar_MVC
{

using System;
    using System.Collections.Generic;
    
public partial class FamilyMembers
{

    public int FamilyMembersID { get; set; }

    public string FullName { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public Nullable<System.DateTime> DateAdded { get; set; }

    public Nullable<int> IcomMembersId { get; set; }

    public Nullable<bool> PrimaryMember { get; set; }

}

}
