
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullCalendar_MVC
{

using System;
    using System.Collections.Generic;
    
public partial class Folder
{

    public long FileID { get; set; }

    public string FileName { get; set; }

    public Nullable<System.DateTime> DateSaved { get; set; }

    public Nullable<int> UserID { get; set; }

}

}
