
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullCalendar_MVC
{

using System;
    using System.Collections.Generic;
    
public partial class IcomMembers
{

    public int IcomMembersId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public Nullable<System.DateTime> DateRegistered { get; set; }

    public Nullable<decimal> AmountPaid { get; set; }

    public Nullable<decimal> AmountCharged { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Country { get; set; }

}

}
