//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCalendar_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaat
    {
        public int SalaatID { get; set; }
        public string Fajr { get; set; }
        public string Dhuhr { get; set; }
        public string Asr { get; set; }
        public string Maghrib { get; set; }
        public string Isha { get; set; }
        public string Khutbah1 { get; set; }
        public string Jumma1 { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Jumma2 { get; set; }
        public string Khutbah2 { get; set; }
    }
}
