
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullCalendar_MVC
{

using System;
    using System.Collections.Generic;
    
public partial class Slides
{

    public long SlideID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public byte[] BackImage { get; set; }

    public byte[] MainImage { get; set; }

    public string DescColor { get; set; }

    public string TitleColor { get; set; }

    public string MoreInfoURL { get; set; }

    public Nullable<System.DateTime> DateAdded { get; set; }

    public Nullable<int> UserID { get; set; }

}

}
