//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCalendar_MVC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class GalleryEvent
    {
        public int GalleryEventID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string EventDate { get; set; }
        public Nullable<int> EventType { get; set; }

    }
    public partial class ImageItem
    {
        public int ImageID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

    }
}
